version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /usr/frontend-app/node_modules
      - .:/usr/frontend-app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/frontend-app/node_modules
      - .:/usr/frontend-app
    command: ["npm", "run", "test"]
